version: "3.8"

services:
  front:
    image: mail-front
    container_name: mail-front-container
    build:
      context: ./web-mail
    volumes:
      - frontend-build:/build

  back:
    image: mail-back
    container_name: mail-back-container
    build:
      context: .
    volumes:
      - frontend-build:/build
      - ./:/server:cached
      - /server/node_modules
    ports:
      - "7003:7003"
    depends_on:
      - front
    deploy:
      resources:
        limits:
          memory: 500M
    restart: on-failure
    networks:
      - shared-pet

volumes:
  frontend-build:

networks:
  shared-pet:
    external: true
